### PR TITLE
Add an NVM file

### PR DESCRIPTION
**Pull request by whyisjake**
Makes it easier to manage NPM versions when dealing with a lot of legacy projects.

### CODE REVIEW

**Comment by zakiya** [comment]
Thank you @whyisjake for your contribution to the California Design System!

- The team and I are discussing and testing the implications of using an nvm config file in the design system. Can I ask why you recommended `.nvm` instead of `.nvmrc`? The latter is in the [nvm docs](https://github.com/nvm-sh/nvm#nvmrc), but the only mention I could find of the former is in the [DreamHost Knowledge Base](https://help.dreamhost.com/hc/en-us/articles/360029083351-Installing-a-custom-version-of-NVM-and-Node-js). We hope to support a variety of platforms and experiences.
- We recommend the LTS version of node (currently 16.14.0) and use it locally and in our build servers.
- Assuming we make this change, we’ll also need to add instructions to the docs.

## Todo

- [ ]  Get team approval
- [ ]  Add .npmrc to all component packages to set v16.14.0
- [ ]  Add instructions for use
- [ ]  Add update instructions
- [ ]  CRM: Give contact to PMs (let them know who is messaging us) - (or chach automates this with airtable somehow)

## Notes for team

- The file is ignored until the command `nvm use` so there won’t be any impact for users who don’t have nvm installed or have to use a different node version due to server requirements.

**Comment by xjensen** [comment]
Another important thing to note is that [nvm](https://github.com/nvm-sh/nvm) doesn't really work on Windows. There are alternative tools, like [nvm-windows](https://github.com/coreybutler/nvm-windows), but they aren't exactly the same. While this is mentioned in the NVM docs, I think it bears repeating here because we'll need to thoroughly test and document the path for Windows devs too.

**Comment by zakiya** [comment]
[After some discovery](https://odi-dev-zk.notion.site/Volta-v-NVM-da0d2fd76fcc40a5aff0a37c34945204) I'm recommending that engineers [Volta](https://volta.sh/) rather than NVM. It has better Windows support and less mental overhead. Since the config doesn't interfere with other engineers' workflow, we'll take an ad hoc approach to its the use and will continue to recommend the use of the Node LTS version for all our projects.

**Comment by m-sullivan7** [comment]
@zakiya Can we move this to the done column?

**Comment by zakiya** [comment]
yes

**Pull request closed without merging**
