### PR TITLE
Issue 741

### PR DESCRIPTION
**Pull request by saldanaj27**
Hi @aaronhans,

So I believe I finally finished the issue. I would love for you to look at the site-navigation component now. Here is the [codepen](https://codepen.io/saldanaj27/pen/RwxQKzJ) copied straight from my code. If there are any thoughts or changes that you would like to talk about, I would be more than willing to set up something. Thanks again.

### CODE REVIEW

**Comment by aaronhans** [comment]
Great work @saldanaj27! Really cool to see you make all this progress on such a massive upgrade. Thanks for the codepen demo as well as the PR. I know the mobile interactivity is especially tricky to get working without javascript. It would help us review if you could describe your process a little bit:
- What approaches did you look into and discard?
- What did you eventually decide on to provide the mobile UI interactions and what are all the elements involved to make it work?

**Comment by saldanaj27** [comment]
Yea, of course! 

So for the desktop view, I kept most of the HTML code. I kept the button tags for the site columns, but you can now hover over them instead of clicking on the button to open the dropdown menu. I added a shadow on the column and dropdown link when hovering to make it more clear what link is being clicked on. While I was going through the code, I did find some blocks of code not being used and others being intentionally hidden. As requested, I removed the code for the google search that was left there but intentionally hidden. I also removed an attribute on the arrow HTML tag that hid the arrow from the screen.  I also changed the CSS code to keep the same design but without the added classes on the HTML tags from the JavaScript code. Other than these edits, I made no other significant changes.

So I wanted to keep the same functionality of clicking on a menu trigger that will open up the menu columns and dropdown links for the Mobile view. I replaced the button element with an input element because I couldn't use the functionality of a button without JavaScript. I saw that you guys had some HTML elements named "hamburger" and "hamburger-box," so I assumed that was what the team had in mind to open the menu, but there was no CSS code that modified or created the design. So, I added a label and span tag to create the hamburger design for the input element. The most significant change in the mobile UI interaction was the HTML code structure. With JavaScript, it was easy to grab a specific HTML tag from anywhere in the code and manipulate another HTML tag even if they were in separate blocks of code. Without JavaScript, to manipulate a part of code with the input element, it had to be either the parent or a sibling. The "site-header" HTML class was the block of code that had the previous mobile icons, but I couldn't open the menu if the input tag were in this class, so I had to put the input and hamburger elements within the "cagov-site-navigation" class. This made the input element a sibling of the expanded menu, which finally allowed me to open it. I kept the site header code, but I did have to comment it out because it created a button from the previous code. 

I added comments throughout the CSS code that explained what each block did so that if the team wanted to create further edits, they could navigate it easily. If there are any more questions, I would be more than willing to answer.

**Comment by aaronhans** [comment]
We got the time to review this and the team is impressed. Excellent work @saldanaj27!

It is really cool to see the desktop fully interactive and the mobile version able to show/hide and expand all the subsections all without any javascript. That is a creative CSS technique to let the submenus expand on mobile based on max-height controlled by hover on a parent. 

This fulfills the goal of letting all the menus be available without the web component javascript executing.

The team consensus is that this is a great approach we can integrate.

There are some things that need to be improved like the ability to close menus in mobile or open items in a different order. Right now it works smoothly when opening one at a time starting at the bottom but not from the top. It may not be possible to achieve all that without javascript which is ok. It makes sense for us to use this initial no javascript version and then use an enhanced version that relies on javascript to provide the perfect interaction patterns.

Congratulations on achieving a difficult goal here!

**Comment by saldanaj27** [comment]
Thank you guys. It was honestly really fun to work on this issue, and I am happy I helped in any way possible!

**Comment by zakiya** [comment]
@aaronhans Can you get this back into a state where it is mergable? If you don't have time this week, please assign it to @xjensen

**Comment by aaronhans** [comment]
Let's chat about this when you have a minute @xjensen. Javier did excellent work here but we have more to do before merging

**Comment by zakiya** [comment]
Closing due to project inactivity. Thank you everyone for the time spent on this issue/

**Pull request closed without merging**
