### PR TITLE
Improve page titles

### PR DESCRIPTION
**Pull request by xjensen**
This PR appends the site's name to every page title.

It also provides a means to edit page titles and descriptions for component pages, as discussed with Content Team.

### CODE REVIEW

**Comment by zakiya** [comment]
On the PR site About and Get Started titles are "California Design System"
https://site-name-appended-to-titles.pr.designsystem.webstandards.ca.gov/about/
https://site-name-appended-to-titles.pr.designsystem.webstandards.ca.gov/get-started/

**Comment by xjensen** [comment]
@zakiya Yep, that's currently the default if there's no title declared for a page. 

This PR is part of a dance with Content Team where they're populating the data and I'm building stuff to display that data at the same time. Some pages just aren't ready yet.

**Review by zakiya — APPROVED** [review]

**Comment by xjensen** [comment]
@m-sullivan7 @ashleydraper @LizNobriga @extinah Question for y'all. 

When there's no title available for a page, do we still want to offer a default title with the site name appended? Or just use the site name as title?

If no title for page...

page title = site-wide default page title | site name

OR

page title = site name

Let me know if I need to clarify here.

**Comment by m-sullivan7** [comment]
My vote is for 2:

> page title = site name

However, if someone else can think of a default title they think is useful, I could be persuaded of 1!

**Comment by LizNobriga** [comment]
I think option 2 works. 

I can't think of a default title that would be appropriate to use for any page.

**Pull request merged**
