### PR TITLE
Task 400/accordion more progressive

### PR DESCRIPTION
**Pull request by aaronhans**
This branch rewrites the accordion component so that it uses the details and summary elements which expand and contract in browsers. by default without any javascript.

It still uses javascript in order to apply open and closing animations.

CSS is modified to hide the default open/closing caret indicator and apply our design with a plus/minus icon only when the javascript executes by using :defined on the custom element name in the CSS selector

The plus and minus icons are created with CSS box shadows so the previously required separate components plus and minus are deleted

This is a breaking change for this component because the recommended markup is changed significantly. The major version is bumped to indicate the breaking nature of the update

### CODE REVIEW

**Comment by chachasikes** [comment]
I see you updated the markup example in `components/accordion/README.md` @aaronhans  - that's great.

Can we sync up on our desired workflow for breaking changes? It's a workflow we are going to need to convert into a step-by-step process so we can keep track of our preferred sequence.

To kick us off:
1. New development breaks markup. 
2. Review the change in general, and also in the component UI.
3. Summarize the markup changes in human-readable format using diff of the change as source info.
4. Draft a communication to PM/content editors on the markup change 
5. Do updates to content - QA the change notification to confirm that it's crystal clear with no issues.

I noticed that the package has already been updated. Did we put this component in a draft mode on npm already? 
If not, it might be good to create a `2.0.0-rc` version of the component for review while co-developing the notification of the breaking change - and then when the messaging about the change is completed, to do the package bump, including guidance on the difference with that version.

I will draft a message in the next comment.

**Comment by chachasikes** [comment]
We could do this in the CHANGELOG

##  2.0.0
* Rewrite to use the details element which expands and collapses without requiring javascript. The javascript remains only for the animation. This radically improves progressive enhancement while reducing code size. 
* Make use of :defined to enhance design styles. This is available after the custom element's javascript has been executed.
### Upgrade notes 2.0.0
* **Updated markup structure** please refer to the [README](components/accordion/README.md) for the latest markup  example. [See diff](link-to-the-diff) 
* When performing this component update, existing accordion markup content will need to be mapped to the new HTML structure in content. Any integrations will also need to update structure and content implementations.

**Comment by chachasikes** [comment]
A couple of other notes came to mind:
* Update component documentation (content model)
* Creating an upgrades page, with some suggestions of how to do this easily for a content team in hand-coded situations.

**Comment by aaronhans** [comment]
Good suggestions @chachasikes thank you! I'll:
- integrate improved changelog text
- review the content model
- open a new ticket for a general upgrades page and we can include dependabot instructions there too

Those are good notes on the upgrade process.

There is difficult for the component consumer so our documentation could emphasize the steps taken before considering implementing a breaking change. 

This is the process we went through so far:
- Need for breaking change is approved by multiple members of design system engineering team
- Update is prototyped and exercised independently of design system code updates
- Multiple engineers review the potential change before integration into the design system is considered
- Publish a -beta version of the npm package with the potential change
- Integrate this change into at least 2 different sites using the component
- Modify site code as required to preserve custom styling
- Verify all component variations in both sites work as expected in all target browsers
- If component has a corresponding Gutenberg block update the block code
- Test updated Gutenberg block plugin by deploying it on site using latest version of WordPress

Todo:
- Summarize the markup changes in human-readable format using diff of the change as source info.
- Draft a communication to PM/content editors on the markup change

Regarding version publishing schedule: I published this as a -beta version while I was upgrading it on covid19 and in the Gutenberg blocks plugin. When those updates were working and ready for review I published the npm package v2.0 so it could be used in the final change request to those codebases. In this case the previous PRs to the design system site had already gone through review cycles against older site release branches.

Good point about an -rc version. This requires multiple updates to the sites where the new version was tested and the custom Gutenberg blocks plugin but we could follow a more conservative process, perhaps:

- PRs to live sites using the component and the custom Gutenberg blocks plugin could go live initially with -rc version of the component's npm package
- The v2.0 version of the component could be published to npm as the design system site change referencing it goes live.
- All sites used for testing the latest version of the component and the custom Gutenberg blocks plugin would receive additional PRs to upgrade to the v2.0 once published

**Comment by chachasikes** [comment]
These are awesome notes! Thank you!

I'll copy this over to our process notes as a sub-page so we don't lose it in the issue log history until it has a forever-home.

This is the kind of stuff that I would expect could help other devs across the State - especially regarding knowing what happens when there are changes and what's involve in submitting a major improvement. 

We could confirm this by sharing our process when new people start using this process.

**Comment by chachasikes** [comment]
(Also note for everyone - I'm the Release Ranger this sprint & I'm noticing process changes & making sure they get handed off to the next ranger)

**Comment by aaronhans** [comment]
You're right, thanks @zakiya

**Comment by aaronhans** [comment]
This shouldn't be merged until we have design approval. After design approval publish latest patch version to npm with changelog describing design fixes

**Comment by aaronhans** [comment]
Thank you @kmbrlygl for the excellent design review:

-[ ] Compared to the [Figma mockup](https://www.figma.com/file/A1DSo765cWjvBWoLd6tvEE/DS-website-screens?node-id=379%3A10012), the +/- icons are a lot bolder. 
-[ ] I notice there are buttons (Hello, Goodbye) in the first accordion but doesn’t look like a button, so seems confusing so maybe we can remove or apply a button style
-[ ] If the point is to showcase the type of content it can contain, maybe we can put a list in another accordion to show versatility
-[ ] We mention using a h2 or h3 heading in the documentation, can we demonstrate that in the demo & markup? (Heading mentions are no longer appropriate so they have been removed from the readme)
-[ ] The second accordion title draws attention to itself and is unclear why. I suggest keeping it all the same or making them all different.
-[ ] Ideas: Title 1, Title 2…. (similar to [Carbon DS](https://www.carbondesignsystem.com/components/accordion/code/)) / Summary Title 1…2…
-[ ] If the point is to show a title that spans two lines, maybe: Title 1: Single-line, Title 2: Multi-line [Lorem ipsum text]

**Comment by aaronhans** [comment]
Thank you @kmbrlygl for reviewing the open icon live with me and tweaking the pixels. The changes we made are live on https://task-400-accordion-more-progressive.pr.designsystem.webstandards.ca.gov/pr/task-400-accordion-more-progressive/components/accordion/readme/

**Comment by aaronhans** [comment]
I am going to modify the changelog. Let me know if you as release ranger want to include this in the release branch it is targeting @chachasikes

**Comment by kmbrlygl** [comment]
Great work @aaronhans! Thanks for your diligence to get this looking great

**Comment by chachasikes** [comment]
@aaronhans 
* No changes to the component, looks good - changes to JS look good
* Are there any accordions in DS page content that will need to be converted?
* Thanks for updating the content model!

**Comment by aaronhans** [comment]
I don't see any accordions in the DS page content outside the accordion readme

Latest version 2.0.1 has been published to npm

This PR is ready for release

**Pull request merged**
