### PR TITLE
815/dependabot updates

### PR DESCRIPTION
**Pull request by chachasikes**
#815

### CODE REVIEW

**Comment by chachasikes** [comment]
Should I validate anything for component/table?

**Comment by zakiya** [comment]
> Should I validate anything for component/table?

I would just run all the build and build:wp scripts locally to make sure there are no changes in the production code if you haven't already. All those dependencies are dev dependencies that probably won't impact the final markup.

**Comment by chachasikes** [comment]
Not seeing any differences in the production code running `build`, `build:wp` inside the `components/table` folder @zakiya

**Review by zakiya — APPROVED** [review]
Assuming the the change to the  design system form was intentional, \looks good to me.

**Comment by zakiya** [comment]
Since this passes vr tests and has security fixes I'm going to merge.

**Pull request merged**
