### PR TITLE
Fix ip dependency

### PR DESCRIPTION
**Pull request by xjensen**
This PR addresses the npm `ip` vulnerability in a somewhat creative way. 

It turns out all of the `package-lock.json` files across components are redundant. This has been the case since we implemented an [npm workspaces](https://docs.npmjs.com/cli/v10/using-npm/workspaces) setup in this repo. Also, because `package-lock.json` is generally not published within npm packages, we don't need to worry about missing anything downstream. 

So, this PR simply deletes all of those `package-lock.json` files. Rebuilds and version updates are also included.

I can publish new versions of all the packages when we're agreed on the approach here.

### CODE REVIEW

**Comment by xjensen** [comment]
Accessibility tests are failing. Need to fix the pagination component.

**Comment by xjensen** [comment]
We now have a tentative fix for the pagination accessibility problem.

In the pagination component, we have an ellipsis that denotes "overflow" when there are too many pages.

Screenshot 2024-02-27 at 09 43 14

For accessibility purposes, we've been applying `role="presentation"` to this ellipsis. But it seems newer versions of accessibility testers don't like this. By rule, a list should only contain active `<li>` elements and nothing else. 

So instead, I've replaced that `role` with an `aria-label` that describes the range represented by the ellipsis. For example, `aria-label="Page 2…4"` (where "Page" is currently a templated word for translation purposes). This felt like a good stop-gap fix for now. But I'm definitively open to suggestions. There are many ways to approach this.

**Review by zakiya — APPROVED** [review]
Do we need the aria-label for tests to pass? It seems redundant here. I tested with VoiceOver and the aria label isn't read on the li, just on the a. Based on [this article](https://www.scottohara.me/blog/2020/05/02/labelled-lists.html), it seem an aria-label on an li will either be ignored or read in addition to the text between the li

**Review by zakiya — APPROVED** [review]
Other than the nitpick about the pagination, this looks good. Please make sure you follow procedures in the wiki for [Publishing a ds components to npm](https://coda.io/d/Engineering-wiki_dL_3_CR2bVn/Publishing-design-system-components-to-npm-CDN_suPjB)

**Pull request merged**
