### PR TITLE
Remove smooth scrolling polyfill

### LINKED ISSUE #808: Bug: anchor links navigate too far above target
This problem has been reported on the design system site by @ashleydraper and on the development.digital.ca.gov site which uses design system components by Regan.

Noticed in sidebar links all over the design system site by Ashley.

From Regan:

The sidebar jump links seem to calculate a higher y-value than needed (maybe 150px off due to header calculation?). Persists across browsers on Mac/iPhone

### PR DESCRIPTION
**Pull request by xjensen**
Fixes #808. Removes the polyfill for smooth scrolling in Safari, as well as the code to manually handle clicks. We're just trusting the browser here.

New versions of Safari are still working through a few bugs in smooth scrolling, particularly when it comes to horizontal scrolling (`overflow-x: hidden`, etc.). But I don't think we face that problem with the page-navigation component. All of my testing thus far has been good.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
Thanks for identifying this as a fix! I love seeing code deletion improving functionality

**Comment by chachasikes** [comment]
From what I remember (from our flurry of building & UX testing on DCC site) - the smooth scrolling was a UX improvement for Safari that prevented sudden jumps when navigating the links.

Looking at your PR

**Comment by chachasikes** [comment]
All good! 

This post discusses that improvement being added last winter! https://forums.macrumors.com/threads/apple-releases-safari-technology-preview-139-with-bug-fixes-and-performance-improvements.2332609/

Included in this release: https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes

(more comments here re: incomplete implementation of smooth scroll - https://stackoverflow.com/questions/72060377/smooth-scrolling-on-safari-15-4-breaks-scrolling-entirely)

We were aiming for vertical scrolling support.

Based on some [old issues](https://github.com/cagov/cannabis.ca.gov/issues?q=scroll) - I'm remembering that there was a UX situation of scroll working on some pages & not others - but I'm not seeing that behavior in Safari (desktop/phone) from your PR branch.

Another (common) testing condition would be "land on page, navigate to anchor" - which would really belong in the global properties for page rendering & not page navigation - and could possibly compete with back to top or other behaviors also playing with scroll.

**Comment by zakiya** [comment]
@chachasikes Was your prior comment just for situational awareness or are you proposing a different solution?

**Comment by chachasikes** [comment]
Situational awareness & validating that it works.

Documenting which specific technology change went into effect that caused a change to a component in the Design System.

**Pull request merged**
