### PR TITLE
Added page alert component

### PR DESCRIPTION
**Pull request by kkoryaka**
Need help with unit test script.

### CODE REVIEW

**Review by chachasikes — APPROVED** [review]
Nice - love the test! : )

**Comment by chachasikes** [comment]
@kkoryaka I see you want help with it. Do you have a plan of what to test?

**Comment by kkoryaka** [comment]
I am trying to test if close button dismisses the alert on click. Also, Would be nice if we can test if it uses ca-gov-icon and if it has aria-hidden true attribute.

**Comment by xjensen** [comment]
@kkoryaka Regarding `aria-hidden` tests, here's [an example](https://github.com/cagov/design-system/blob/8e69a5c45affe1213a23dbc9e8cfb71dba5a149e/components/accordion/test/index.test.js#L28-L30) of how to test ARIA attributes in the ds-accordion component. Just replace `aria-expanded` with `aria-hidden` (and add your own class name). Should work the same way.

Hopefully that's helpful. Let me know if not, I'd be happy to jump in and help further.

**Pull request merged**
