### PR TITLE
Added buttons styles to base-css

### PR DESCRIPTION
**Pull request by kkoryaka**
Added buttons section to the design system style guide page. For now we have agreed to use just primary color buttons variations. Once design team decides on secondary colors we can add secondary variations.

Screen Shot 2022-02-01 at 10 18 09 AM

### CODE REVIEW

**Review by kmbrlygl — CHANGES_REQUESTED** [review]
Overall, looks good for now! One thing I noticed is the primary outline button has an anchor to it `href="#" `but the primary button does not. Should they both not have an anchor? I think it's best if they are not functional just for demo purposes.

**Comment by kkoryaka** [comment]
@kmbrlygl I just give two ways of using this button styles: one with actual `button` tag and one with `<a>` tag (as a link), It's good for developer to know that they can use those styles with both tags.

**Review by kmbrlygl — APPROVED** [review]
Oh okay. Then I think good to go then.

**Comment by aaronhans** [comment]
@kkoryaka please target this to https://github.com/cagov/design-system/tree/1.0.1-rc-post-launch-fixes instead of main so we can group the next batch of site changes

**Review by aaronhans — COMMENTED** [review]
Nice work!

Thanks for documenting the options so well

**Pull request closed without merging**
