### PR TITLE
ds-dropdown-menu enhancements

### PR DESCRIPTION
**Pull request by xjensen**
This PR aims to bring drought.ca.gov compatibility to the ds-dropdown-menu component. 

The Drought site does not yet have enough content for dropdown lists, so the menu component needs to allow proper spacing and alignment for simple static links (without the dropdown arrow icon).

This PR also includes a fix to the scenario shown in the following screenshot. When a desktop screen is narrow, the right-most dropdown menu can get clipped.

Screen Shot 2021-09-27 at 15 10 29

The fix included here aligns that last dropdown to the right edge of the design, like this.

Screen Shot 2021-09-27 at 15 38 44

We may want to treat this scenario differently. Let me know if so.

### CODE REVIEW

**Comment by kkoryaka** [comment]
Fixes look great. The only problem I see in aesthetics of focus outline, It outlines only button and doesn't have and right and left padding as well as not including little icon. Because of my design background it bugs me. Doesn't look professional. Would you consider include entire button into focus and give it enough breathing room since people use this component a lot? Or will break all your improvements to it?

Screen Shot 2021-09-27 at 5 10 06 PM

**Comment by aaronhans** [comment]
FYI We are getting more drought content which will probably require some drop down menus

Love that you fixed the focus outline. Good catch @kkoryaka

I don't have a solution for this padding issue. We want less padding when there is no visible arrow

**Comment by kkoryaka** [comment]
I am thinking maybe aligning all menu items to the left side, that way at least we don't have to worry about the right side alignment, and it also go in line with figma prototypes designs. We can play with padding/or negative padding on the left to make it look aligned  where text starts (not necessarily where actual button starts)
Screen Shot 2021-09-29 at 11 02 01 AM

**Comment by xjensen** [comment]
That makes a lot of sense, @kkoryaka. Should I merge these changes now, then we'll address padding and menu-items-left-alignment in an upcoming change?

**Comment by xjensen** [comment]
@kkoryaka I've applied some changes here. Menu items are now left aligned, with a gap between of 24px. I've also fixed the padding within menu items, so focus looks better.

Screen Shot 2021-09-30 at 11 49 23

Screen Shot 2021-09-30 at 11 48 26

Screen Shot 2021-09-30 at 11 31 58

Let me know if you think this is ready to go. I'll need to put a couple of changes into Cannabis and Drought afterwards.

**Pull request merged**
