### PR TITLE
Links added to images in 4 types of cards

### PR DESCRIPTION
**Pull request by alexhu00**
**4 Types of Cards Changed**
- Component Cards *(Put <a> tag around it with href)*
- Homepage "What's in the Design System" Cards *(Put <a> tag around it with href)*
- Homepage "Principles for people-centered digital services" Card *(Replaced <div> with <a> tag with href and classes)*
- Homepage "Who Using it" *(Replaced <div> with <a> tag with href and classes)*

Re: Issue 764

### CODE REVIEW

**Comment by aaronhans** [comment]
Excellent pull request! Thanks @alexhu00!

It looks like the package-lock update is happening because it is using an older lockfileVersion. We use node v16 and npm v7 for this project. npm chnaged to lockfileVersion 2 in npm v6 so using an older version of npm will produce a totally different lockfile format.

The easiest update to the PR is to remove the package-lock changes

**Comment by aaronhans** [comment]
The automated PR validation for accessibility caught an issue: 
│    0    │ 'link-name' │ 'serious' │ 'Ensures links have discernible text' │  19   │

This test can be run locally with ```npm run test:site```

It is powered by axe. There is a free axe chrome plugin https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US which you can run against the site running locally to make sure it isn't catching anything too

^ These are things we should add to the developer documentation. Thanks for running into them!

**Comment by aaronhans** [comment]
Here is more info on the accessibility rule axe is complaining about https://dequeuniversity.com/rules/axe/3.5/link-name

**Comment by alexhu00** [comment]
@aaronhans 
- Downloaded axe
- Added a11y link text for the components svg to resolve the automated PR accessibility validation issue
- Reverted package-lock.json to original version from main

**Comment by aaronhans** [comment]
This looks great! Thanks @alexhu00 

[x] I ran the branch locally, links look good
[x] CSS updates included look like prettier formatted some color strings
[x] Accessibility checks are passing now

One more step then we can merge into the next release:

- Please make this PR against our 1.0.5-albany branch instead of main. We are grouping a bunch of changes into big releases every couple of weeks until we have full test coverage on the site.

**Comment by alexhu00** [comment]
Thanks @aaronhans! Just changed the base branch to release/1.0.5-albany. Let me know if this is sufficient.

**Review by aaronhans — APPROVED** [review]
Excellent, thank you!

**Pull request merged**
