### PR TITLE
Adding suggestion for Immersive Reader mode

### PR DESCRIPTION
**Pull request by mgifford**
This is just another useful way to help authors write better.

### CODE REVIEW

**Comment by ashleydraper** [comment]
Hi @mgifford!
Thank you so much for your suggestion on the Immersive Reader in Microsoft Edge.
I am the lead content designer for the design system and I'm very curious about this tool. 

My colleagues and I took a look at the features and tested it. Can you share what you find most useful about the Immersive Reader tool? This is new to us, so we're really excited to learn more and hear about your specific use case.

**Comment by mgifford** [comment]
Hey @ashleydraper I often just use it more as an editing tool. Sometimes if you can hear what you've written you can find ways to improve your writing. For me that's one of the biggest advantages. Also, a lot more content is being read aloud, by tools like Alexa, Siri or Google Home. Just nice to have a way to hear what this might sound like. 

There are people who use the reader mode to just reduce the distractions and focus in on what they are reading, or to have the text read to them. We know that since we are all spending more time in front of screens it can be nice to have content presented to you non-visually. 

Now we could all just use a free or built-in screen reader, but frankly this is easier and generally does a more natural sounding job.

**Comment by ashleydraper** [comment]
I kinda love that! It would offer support to all of my team's sentences that begin with, "now when screen readers read this..." :D 

Thanks so much again for raising this. Let me discuss with my colleagues and get back to you.

**Comment by ashleydraper** [comment]
@mgifford Closing the loop on this thread. We are closing this pull request and have addressed this recommendation in #897. This content will be available to view live on the site in the next release. 

Thank you so much for this contribution!

**Pull request closed without merging**
