### PR TITLE
Linting and Testing Mega-PR

### PR DESCRIPTION
**Pull request by xjensen**
Let's add linting and testing to all of our components.

Here are the corresponding Issues.

* #175 
* #176 
* #177 
* #178 
* #179 
* #180 
* #181 
* #182 
* #183 
* #184 
* #185 
* #186 

This is a draft. I imagine we'll want to split this up into separate PRs for each component once it's all working.

### CODE REVIEW

**Comment by xjensen** [comment]
Looks like we now have tests for every component except base-css.

**Comment by xjensen** [comment]
Merged the latest from `main`, added tests to newer components. 

FWIW, I did not add a test to `combined-css` because I didn't see much value in it. It's an exercise in bundling, where all the included components are covered by their own tests. `build` seems like enough to catch problems. Open to interpretation though; let me know if we need a test here.

**Comment by xjensen** [comment]
Bumped version numbers and edited changelogs for all components.

**Comment by aaronhans** [comment]
Tested all components with code changes in chrome and safari on headless cannabis using versions published to npm with the beta tag

**Comment by xjensen** [comment]
Tested all beta components in Drought for the following browsers.

* Chrome (Mac, PC)
* Firefox (Mac, PC)
* Safari (Mac, iPhone)
* Edge (PC)

Looks good! I'm going to set this PR ready to review.

**Review by aaronhans — APPROVED** [review]
so pretty, lint free and tested!

**Pull request merged**
