### PR TITLE
binco-bears.svg

### PR DESCRIPTION
**Pull request by Angsv**
file upload of binco bears SVG file for 404 page.

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
these are very cute

**Comment by chachasikes** [comment]
@Angsv The bears look great.

We could simplify the file name if `SVG_` isn't needed as a prefix. 

Otherwise, looks good & has the SVG file extension - all good!

**Comment by Angsv** [comment]
@chachasikes whatever naming convention makes the most sense for the developers is fine with me.

**Comment by chachasikes** [comment]
@Angsv  OK - I updated it & added a note - we haven't declared a naming convention yet - but edited it to match what we have so far (plain language file names, no extra stuff, using dashes instead of underscores)

Thank you so much!! WE LOVE THE BINOCULAR BEAR!!

**Pull request merged**
