### PR TITLE
July 2023 updates

### PR DESCRIPTION
**Pull request by xjensen**
Addresses issues: 

* #973
* #974

Regarding the GA4 statewide tracking code, I'm not sure if I got our "individual agency ID" correct (`G-PJDVH1C2JS`). Who can confirm this detail?

### CODE REVIEW

**Comment by xjensen** [comment]
Checking with Regan re: verification of the agency ID for GA4.

**Comment by jbum** [comment]
@xjensen I believe G-PJDVH1C2JS is the one used by DCC, and not relevant here.  Last I asked the data team if they had an individual ODI code, I got "No, we have not. We’re not really doing much with GA4 right now."

**Comment by xjensen** [comment]
@jbum That's good context. One wrinkle though: I pulled that code (G-PJDVH1C2JS) from innovation.ca.gov. 

Do you think it's okay to use it here on Design System in the same way that it's used on Innovation? Or should we get to the bottom of this?

**Comment by jbum** [comment]
Hmm,  possibly cut and pasted by someone.  I originally received that ID here, and used it on the Cannabis site:

CleanShot 2023-07-10 at 15 38 16

**Comment by reganking** [comment]
@jbum I'm checking with David right now about the origin.

**Comment by reganking** [comment]
@xjensen I suggest using G-69TD0KNT0F for the time being.

**Comment by xjensen** [comment]
David at CDT confirmed the code for this site should be `G-65PBRKRPK6`. Made the change. Ready for review again. 

Many thanks @reganking and @jbum for helping look into this.

**Review by zakiya — APPROVED** [review]
Looks good to me

**Pull request merged**
