### PR TITLE
Rename components

### LINKED ISSUE #367: Update component file names to match updated names
Not a priority. Do this when there is time. Example: content navigation is now page navigation. Update the component name (including the design system web page).

### PR DESCRIPTION
**Pull request by xjensen**
Update component names to match latest documentation.

| Previous name | New name |
| --- | --- |
| ds-feedback | ds-page-feedback |
| ds-agency-footer | ds-site-footer |
| ds-branding | ds-site-header |
| ds-content-navigation | ds-page-navigation |
| ds-menu | ds-site-navigation |
| ds-button-grid | ds-link-grid |

This PR doesn't just rename the npm package. It also updates names of key custom element and/or CSS classes to match. (The following changes are documented in component changelogs too.)

* Custom element `<cagov-content-navigation>` becomes `<cagov-page-navigation>`.
* Custom element `<cagov-feedback>` becomes `<cagov-page-feedback>`.
* Custom element `<cagov-navoverlay>` becomes `<cagov-site-navigation>`.
* CSS class `agency-footer` becomes `site-footer`.
* CSS class `branding` becomes `site-header`.

Changes to these components required modifications to `ds-link-icon` and `ds-combined-css` as well. Those changes are included here.

Tests were failing in `ds-page-navigation`, so I also fixed part of the Javascript in that component.

Finally, the Design System site is updated to reflect these changes.

Closes #367.

### CODE REVIEW

**Comment by xjensen** [comment]
Changes are complete. Moving on to testing on our sites.

**Comment by xjensen** [comment]
Seems to be working well in the Design System site, cagov/drought.ca.gov#261, and cagov/cannabis.ca.gov#470. So I'm setting this at ready to review.

Here are the changes that need to be applied to site mark-up.

* Custom element `<cagov-content-navigation>` becomes `<cagov-page-navigation>`.
* Custom element `<cagov-feedback>` becomes `<cagov-page-feedback>`.
* Custom element `<cagov-navoverlay>` becomes `<cagov-site-navigation>`.
* CSS class `agency-footer` becomes `site-footer`.
* CSS class `branding` becomes `site-header`.

**Review by kkoryaka — APPROVED** [review]
Great work!  make total sense.

**Comment by zakiya** [comment]
Heroic effort! I clicked through the relevant components in the preview and everything looks great!

**Pull request merged**
