### PR TITLE
2022 01 26 page navigation

### PR DESCRIPTION
**Pull request by chachasikes**
Testing on pr server

### CODE REVIEW

**Comment by chachasikes** [comment]
Hey everyone,

To solve an issue with page navigation not working on Windows machines, I've rearranged the scrollTo behavior.

* Keep a "jumping" scroll on all pages (so the anchor links can go to the right spot)
* Move the `behavior: smooth` to html in `_page.scss` and provide a motion reduced option on the behavior

Couple questions:
* @kkoryaka Where in base-css should the markup live - is _page.scss a good spot?
* Any other issues with this?

**Review by kkoryaka — APPROVED** [review]
looks like you are trying to improve scrolling animation behaviors. I wonder if those transition variables are good candidates to our design tokens library

**Comment by chachasikes** [comment]
@kkoryaka How were you thinking they might fit in as design tokens?
I see our _variables.scss file. 

These are the animation variables:
  --animation-duration: 1s;
  --transiton-duration: 0.5s;
  

Would something like this work?
_variables.scss:
Add: 
```
  --scroll-animation-duration: 1s;
  --scroll-transition-duration: 0.5s;
```

And then:
_page.scss
```
 :root {
  --animation-duration: var(--scroll-animation-duration, 1s);
  --transiton-duration: var(--scroll-transiation-duration, 0.5s);
}
```

**Comment by kkoryaka** [comment]
We can definitely add animation variables to our tokens. (here is tokens library example page with animations and easing sections. https://open-props.style/) I put them into base-css _variables.scss file

**Pull request merged**
