### PR TITLE
608 Icons component

### PR DESCRIPTION
**Pull request by zakiya**
Address #608 

Waiting for

- [x]  #678 
- [x] #679

### CODE REVIEW

**Comment by chachasikes** [comment]
Screen Shot 2022-03-09 at 9 57 51 AM

Minor issue - slight overlap on top left icon

**Review by chachasikes — DISMISSED** [review]
This looks good.

Couple of changes before I approve
* Can you merge this to the release branch instead of main?

Minor issue that we can do in QA fixes - some of the icons get clipped on their bottom margins - in the code sample and also narrow screen, icons such as `accessibility`

Screen Shot 2022-03-09 at 10 01 28 AM

**Review by chachasikes — APPROVED** [review]
Love the README!
Will try this component on a project - need some icons on cannabis data viz - will let you know how it goes.

**Review by kkoryaka — APPROVED** [review]
looks great, the only small item that i have noticed is that instagram icon is missing.
Screen Shot 2022-03-22 at 9 42 24 AM

**Review by zakiya — COMMENTED** [review]
@LizNobriga I think I introduced a bug when I tried to update the link destination. Instead of linking to the external library and a blank page `https://california.azureedge.net/cdt/statetemplate/5.6.1/fonts/CaGov.svg`,  I'd link to link to the Icon library on this page `#icon-library` is that okay?

**Comment by zakiya** [comment]
@kkoryaka Fixed the share-instagram icon. The trouble was uppercase vs lowercase. Good catch!

CleanShot 2022-03-22 at 12 08 32

**Comment by LizNobriga** [comment]
> @LizNobriga I think I introduced a bug when I tried to update the link destination. Instead of linking to the external library and a blank page `https://california.azureedge.net/cdt/statetemplate/5.6.1/fonts/CaGov.svg`, I'd link to link to the Icon library on this page `#icon-library` is that okay?

That makes sense. The anchor will work once the icons page is live, right?

**Pull request merged**
