### PR TITLE
574 contact us form

### PR DESCRIPTION
**Pull request by chachasikes**
* #574 contact us changes
* Merge content changes from production (Verified as OK with content team - they are not pushing to staging)

### CODE REVIEW

**Review by kkoryaka — APPROVED** [review]
nice contact form edits.

**Review by zakiya — APPROVED** [review]

**Comment by zakiya** [comment]
May have approved too quickly. Is there a separate task to add an error message if a required field is empty and user hits submit?

**Comment by chachasikes** [comment]
We don't have a design pattern for handling this yet. (Also the default required errors should be in place, so need to sort out what's broken more specifically.

Let's make sure the UI part is assigned to Adam and then we can build this out in the next sprint & also accommodate other accessibility fixes.

**Comment by chachasikes** [comment]
I have a new PR coming that fixes merge conflict - this was done before we set up the release pattern for this sprint.

**Comment by chachasikes** [comment]
NVM, the conflict is resolved.

**Comment by chachasikes** [comment]
I'll check the issue

**Pull request merged**
