### PR TITLE
Task 244/nav menu design flexibility

### PR DESCRIPTION
**Pull request by aaronhans**
These changes allow this component to work if the hamburger menu open button is placed outside the component which is necessary in latest design.

### CODE REVIEW

**Comment by aaronhans** [comment]
FYI @kkoryaka I have this installed in the latest version of the kk-header-layout branch in cannabis. I can move the other files changes into components from there too

**Review by chachasikes — APPROVED** [review]
- awesome (and satisfying) namespace & scoping fixes
- CSS changes

Q: this.querySelector vs. document.querySelector change:
1. How come you are setting scope to document? (Wondering if that's for event tracking or listeners, or another logic issue?) - personally I like the idea of component specific interactions only in the scope of the component - so wondering what you came across that prompted this change.
2. There should be just one menu - AND if we had variants or visual regression tests, there could be multiple variants of the component (e.g. light & dark versions), so querySelectorAll might be needed to add class correctly (unless I'm wrong about that)

**Comment by chachasikes** [comment]
I see your note about "outside the component"

**Comment by chachasikes** [comment]
ok yeah, will need to digest the idea of external buttons - but querySelectorAll could help this work with Dark mode visual tests

**Comment by aaronhans** [comment]
Thanks for reviewing, yeah this is an interesting situation. The mobile menu hamburger button is an integral part of the nav component so it doesn't seem appropriate to have it be a totally separate component that communicates via custom events or something. I also didn't want to make the whole branding section part of the nav but that is still a possibility.

There is definitely more work to do with style scoping, also with how this component can progressively enhance

**Pull request merged**
