### PR TITLE
Updated color palette, standardized buttons

### PR DESCRIPTION
**Pull request by kkoryaka**
Updated design system base-css variables with new color palette based on CEILAB color system documentation
https://docs.google.com/document/d/1xRHMQ_BFYTBI48Jgs9IuKoyrZOfMe-Hho_HhmpXvGB8/
Updated color section in the design style guide page:
https://1-0-6-color-buttons.pr.designsystem.webstandards.ca.gov/style/design/#color

Standardized buttons variations and styles to reflect buttons design documentation in figma:
https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/UI-Design-kit?node-id=99%3A3303

Updated buttons section in the design style guide page:
https://1-0-6-color-buttons.pr.designsystem.webstandards.ca.gov/style/design/#buttons

Added design tokens page back (removed animations and transition tokens from it)
https://1-0-6-color-buttons.pr.designsystem.webstandards.ca.gov/style/tokens/

Standardized buttons in the components that are displayed on the homepage.  
https://1-0-6-color-buttons.pr.designsystem.webstandards.ca.gov/

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
Nice @kkoryaka! Thanks for digging into the a11y checker flagged color contrast issues and bumping components to provide fixes

**Review by m-sullivan7 — APPROVED** [review]
I had already worked on the color section with @kmbrlygl, so I had no changes to that section. I made some grammar edits to the button section.

With those included, looks good!

**Review by kmbrlygl — APPROVED** [review]
This all looks good. Great work Konstantin!

I added some content to the design tokens page to provide context as to why we use Vietnamese in the example for line height.

**Comment by yesenia-gtz** [comment]
Good to go @timothyshambra, Thank you!

**Pull request merged**
