### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by zakiya**
@xjensen @aaronhans I think we still need to do some thinking on the sample markup vs demo. I think the markup that the demo is showing is confusing when taken on a per-component basis. For instance, the accordion demo references /builds/accordion-esm.js. which would not be available if one was using npm to install the component. 

I think I may need to go back to my original idea of referencing the component's template.html or equivalent file.

Als @xjensen I commented out the build command from the pre-commit hook since it was preventing me from committing (`build command not found` ) and  I wasn't sure what the `--workspaces` flag does.

### CODE REVIEW

**Comment by xjensen** [comment]
Yep, good observations re: `/builds/accordion-esm.js` on the Accordion readme. As discussed earlier this morning, that's not something we want in the final document. 

Here's an explanation of what's happening with the workspaces.

The `--workspaces` command works in tandem with a flag in the `package.json` file...

```json
"workspaces": [
    "./components/*"
],
```

This defines the "workspaces" for this project as all the subfolders of `components`. Then when we run a `--workspaces` command, it'll run the given command across every available `package.json` files in those component folders.

For example: `npm run build --workspaces` would run `npm run build` across every component folder. 

When we see that error, `build command not found`, usually we can bypass by just adding an empty 'build` script into the `package.json` file for that component. Something like this.

```json
"scripts": {
    "build": "echo \"WARN: no build specified\" && exit 0"
},
```

Hopefully that makes sense, and hopefully the example works. Please do let me know if I can clarify anything.

For the record, I'm not a huge fan of this approach. It's slow, and it breaks easily as you've seen. I'd rather centralize the build and test activities into unified scripts/processes if possible.

**Comment by zakiya** [comment]
@xjensen Thank you for the thorough explanation. I see what you mean though. That's a massive a lot of work for a pre-commit hook. My GUI (SourceTree) doesn't like it at all. Were you by-passing the hook locally by putting  `"build": "echo \"WARN: no build specified\" && exit 0"` in package.json and not committing it?

**Review by kkoryaka — APPROVED** [review]
I like the consistency and clean look of it (no more bulky HTML code in the readme files.)

**Comment by xjensen** [comment]
@zakiya We added that bypass hook into a lot of the per-component `package.json` files while we were working on the big lint/test PR a couple months back. But I haven't needed to add it to anything locally since then. It all works okay, just so slowly.

Oddly enough, the `npm run build --workspaces` command works fine for me when I check out your branch. Does it work when you run it in terminal vs. your GUI? Just curious for troubleshooting purposes; I want to ensure we can support all kinds of git tooling.

**Pull request merged**
