### PR TITLE
Update font size documentation

### PR DESCRIPTION
**Pull request by kmbrlygl**
Updating font size documentation to include rems sizing for desktop and mobile to better match what Konstantin said is in the CSS

### CODE REVIEW

**Review by kkoryaka — APPROVED** [review]
Looks good!

**Comment by kkoryaka** [comment]
@kmbrlygl I wonder if you can make same PR to 1.0.1-rc-post-launch-fixes branch so @aaronhans would add it to our next release.

**Comment by kmbrlygl** [comment]
@kkoryaka I asked Aaron and he told me to create a PR off of main for this since it's just content changes (nothing too complex). I think this can be merged along with the next release or whenever feels appropriate. Is that how it should go @aaronhans?

**Comment by aaronhans** [comment]
This looks good, we can release it outside of the code change process because it is a content change and I will merge main back into the release branch.

Thank you @kmbrlygl and @kkoryaka!

**Pull request merged**
