### PR TITLE
Move component CSS inserts into custom elements

### PR DESCRIPTION
**Pull request by xjensen**
Addresses #914 by moving CSS insertion into each custom element's constructor. This removes the `const style` from global scope in each file, which may assist in some multi-component build scenarios.

Affected components include the following.
- accordion
- back-to-top
- combined-css
- page-alert
- page-feedback
- page-navigation
- pagination

### CODE REVIEW

**Review by aaronhans — APPROVED** [review]
cool, cleaner now

**Comment by zakiya** [comment]
@xjensen have these changes been pushed to npm?

(Something to think about for the whole team: Can we have a way of knowing/ensuring packages are updated on npm without asking on an individual basis?)

**Comment by xjensen** [comment]
@zakiya No, not yet pushed to NPM. I could push beta versions if needed.

Also, do you want me to merge this into the release branch now, or toward the end of the sprint?

(Ideally we could come up with a script that would do all the publishing to NPM based on changed version numbers, so nobody would need to go through each component.)

**Comment by zakiya** [comment]
Merge now please. 

Sprint ends at the end of the quarter (September) so let's publish to npm now so changes can be available to Danny.

(🤔 )

**Pull request merged**
