### PR TITLE
Cdn hooks pt 1

### PR DESCRIPTION
**Pull request by aaronhans**
Adding the prepublish hooks to the javascript modules to:

- Publish to CDN before publishing to npm
- Share the sample markup between the local component test, preview file and markup in readme
- Create dist folder if that didn't exist for CDN deploy

### CODE REVIEW

**Review by chachasikes — COMMENTED** [review]
High five!

Commenting so Zakiya or Jon can approve for more visibility.

**Comment by aaronhans** [comment]
Thanks for checking this out folks. I'll install the major version bumps in latest versions of drought and cannabis before taking this out of draft

**Comment by aaronhans** [comment]
These component versions are all published to npm, tested in cannabis

An issue with publishing to the CDN where S3 was not applying correct mime types has been corrected by defining mime type on upload

**Review by kkoryaka — APPROVED** [review]
This is massive release.  Thanks!

**Review by kkoryaka — APPROVED** [review]
Thanks!

**Pull request merged**
